model:
  name: "RotateLayer"
  params:
    initial_angle: 0.0

training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.1
  optimizer: "RMSprop"
  scheduler: 
    name: "StepLR"
    params:
      # gamma: 0.9
      step_size: 3
  target_angle: 1.5707963267948966  # np.pi/2
  log_interval: 10
  viz_interval: 5
  device: "cuda"
  save_folder: "experiments"
  

data:
  dataset: "CIFAR100"
  root_dir: "./data"
  train_batch_size: 32
  val_batch_size: 32
  num_workers: 4

wandb:
  project: "rotate-cifar"
  entity: "dean707dark"